# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginVacation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authemployee',
            name='employeeNumber',
            field=models.IntegerField(default=6600541),
            preserve_default=False,
        ),
    ]
