# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginVacation', '0002_authemployee_employeenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authemployee',
            name='employeeNumber',
        ),
        migrations.AddField(
            model_name='authemployee',
            name='realName',
            field=models.CharField(default=6600541, max_length=50),
            preserve_default=False,
        ),
    ]
