# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginVacation', '0004_authemployee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authemployee',
            name='department',
            field=models.CharField(choices=[('nw', 'IDC_Network'), ('sr', 'IDC_Technology'), ('sa', 'Administrator')], default='nw', max_length=2),
        ),
    ]
