# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarModule', '0002_auto_20170927_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('nw', 'IDC_Network'), ('sr', 'IDC_Technology'), ('sa', 'Administrator')], default='nw', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacationDate',
            field=models.DateField(),
        ),
    ]
